name: iotivity-smarthome-demo
version: 0.4
summary: IoTivity SmartHome Demo
description: The IoTivity based SmartHome demo snap
confinement: strict  # use 'strict' once the snap have the right plugs and slots
grade: devel         # use 'stable' for releasing to candidate/stable channels

apps:
  start-iot-rest-api-server:
    command: node $SNAP/lib/node_modules/iot-rest-api-server/index.js
    daemon: simple
    plugs: [ network-bind ]

  run-gateway-server:
    command: env NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/iot-rest-api-server/node_modules node $SNAP/gateway/gateway-server.js
    plugs: [ network-bind ]

  node:
    command: env \
      LD_LIBRARY_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node/iotivity-installed/lib:$LD_LIBRARY_PATH \
      NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/iot-rest-api-server/node_modules \
      node
    plugs: [ hardware-observe, home, network-bind ]

  hciconfig:
    command: bin/hciconfig
    plugs: [ bluez, bluetooth-control ]

  rfkill:
    command: usr/sbin/rfkill
    plugs: [ network-control ]

parts:
  # Part adding SmartHome-Demo local repo
  local:
    plugin: dump
    source: ../
    filesets:
      gateway-files: [ gateway/* ]
      ocf-server-files: [ ocf-servers/* ]
    prime: [ $gateway-files, $ocf-server-files ]

  # Part installs iotivity, iotivity-node, iot-rest-api-server
  meta-iot-web:
    plugin: nodejs
    source: https://github.com/01org/iot-rest-api-server.git
    source-branch: master
    node-packages:
      # adding gateway-server dependencies
      - express
      - websocket
      # adding additional node.js modules
      - mraa
      - jsupm_i2clcd
      - noble
      - bleno
    filesets:
      exports: [ bin/*, lib/* ]
    stage: [ $exports ]
    prime:  [ $exports ]

  # Part installs Ubuntu packages
  ubuntu:
    plugin: nil
    stage-packages:
      - rfkill          # provides /usr/sbin/rfkill
      - bluez           # provides /bin/hciconfig
